name: hitNet

channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - jupyter
  - jupyterlab
  - scipy
  - librosa
  - imutils
  - opencv
  - av
  - pytorch:cudatoolkit=11.3
  - pytorch:pytorch
  - pytorch:torchaudio
  - pytorch:torchvision
  - pip
  - pip:
    - madmom
    - futures
    - torchinfo
    - qqdm
